### PR TITLE
Properties keeping and multi feature

### PR DESCRIPTION
**Pull request by jevy-wangfei**
- Support geojson Point
- Support properties keeping
- Support multi feature and feature's properties keeping
- Reduce the duplicated DGGS cells
- Add test

### CODE REVIEW

**Comment by jyucsiro** [comment]
Hi @jevy-wangfei 

This PR looks great! 
* Geojson Point works
* Support for keeping properties works
* Support multi feature and feature's properties keeping
* Reduce the duplicated DGGS cells works

There was a problem when I used a test where the DGGS resolution was low (i.e. between 4-7) - the resulting feature list was empty. 

Test case URL:
http://localhost:3000/api/search/find_dggs_by_geojson?resolution=7&dggs_as_polygon=True&keep_properties=True

Data attached: 
[BlackMountain3.zip](https://github.com/CSIRO-enviro-informatics/AusPIX_DGGS_API/files/4767794/BlackMountain3.zip)

Response from the API:
```
{
  "type": "FeatureCollection",
  "name": "BlackMountain3",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "features": []
}
```

Can you check if you're also getting this? It might be just my dev environment.

**Comment by jevy-wangfei** [comment]
Hi Jonathan, 

I checked the code and find that `cells_in_poly` (at `auspixdggs.callablemodules.dggs_in_poly_for_geojson_callable`) returns an empty array with the given geojson and resolution. 
Is it possible that the resolution is too large and the DGGS cell is not `in` the polygon?

**Comment by jyucsiro** [comment]
> I checked the code and find that `cells_in_poly` (at `auspixdggs.callablemodules.dggs_in_poly_for_geojson_callable`) returns an empty array with the given geojson and resolution.
> Is it possible that the resolution is too large and the DGGS cell is not `in` the polygon?

@jevy-wangfei ok so the empty array is what's returned from the `auspixdggs.callablemodules.dggs_in_poly_for_geojson_callable` module. 

@bellie888 - how do you handle the case where the DGGS cell returned is larger than the polygon? we will need to update the `auspixdggs.callablemodules.dggs_in_poly_for_geojson_callable` to handle that case. Do you have an example?

**Review by jyucsiro — APPROVED** [review]
The basic functionality of this PR works well. The underlying engine has an issue when the DGGS resolution is coarse (e.g. level 3-5). An issue in the GA repo has been created https://github.com/GeoscienceAustralia/AusPIX_DGGS/issues/13

Approving this PR though based on what it is supposed to do.

**Pull request merged**
